attempt 3 with addding api
abitblue/automactic pull request #19
Opened 2022-08-02 13:04 UTC by AntoDono

2022-08-02 13:23 UTC, IvanZ505 commented on interface/api-automatic.py
> +                                'sponsor_name': 'oauth2:automatic',
Sponsor name is not necessary.

2022-08-02 13:23 UTC, IvanZ505 commented on interface/wrapper.py
> +            self.mac = response['mac']
Does not account for devices with multiple mac addresses.

2022-08-02 13:23 UTC, IvanZ505 commented on interface/wrapper.py
> +    sponsor_name: str = None
this is not necessary too

2022-08-02 13:23 UTC, IvanZ505 commented on interface/api-automatic.py
> +    def _get_expire_date(self, year: str) -> str:
get expire action does not account for other usertypes such as teachers or guests.

2022-08-02 13:23 UTC, IvanZ505 commented on interface/api-automatic.py
> +                        print(self.token)
remove print statement for prod version

2022-08-02 13:59 UTC, abitblue requested changes

2022-08-02 13:59 UTC, abitblue commented on interface/wrapper.py
> +    sponsor_name: str = None
specifically, "sponsor_name" is not necessary

2022-08-02 13:59 UTC, abitblue commented on interface/api-automatic.py
> +        self.check_token()
Why are we checking token twice?
`check_token()` also takes a parameter, where is it?

2022-08-02 13:59 UTC, abitblue commented on interface/api-automatic.py
> +                        print(self.token)
Or, using the logging framework. Search `logger.log` in the codebase.

2022-08-02 13:59 UTC, abitblue commented on interface/api-automatic.py
> +    def add_device(self, mac: str, device_name: str, notes: Optional[str] = None, enabled: bool = True, year: Optional[int] = 4) -> dict:
device_name and notes is ambiguous with the rest of our code
This class should handle the conversion for "formatted_username" (ie. S:michael.whalen@sitechhs.com) and "device_name" (ie. my ipad), which are `device_name` and `notes`, respectively.

2022-08-02 13:59 UTC, abitblue commented on interface/api-automatic.py
> +                            }, verify=False
Not ready for change. Repeated lines throughout file.

2022-08-02 13:59 UTC, abitblue commented on interface/api-automatic.py
> +    def add_device(self, mac: str, device_name: str, notes: Optional[str] = None, enabled: bool = True, year: Optional[int] = 4) -> dict:
`year` is not enough fine-grained control. Please allow a `datetime.timedelta` or a `datetime.datetime` instead.

2022-08-02 13:59 UTC, abitblue commented on interface/api-automatic.py
> +                            self.current_time
Probably not a good idea to wait until the very last moment to refresh. Probably should instead refresh the token  bit before the expire time (perhaps 60 seconds), to account for processing time in the code below.

2022-08-02 13:59 UTC, abitblue commented on interface/api-automatic.py
> +        res = requests.post(f"{self.base_url}/device",
Missing `start_time` field. The server Clearpass is hosted on doesn't seem to have NTP enabled, so there is a significant amount of clock drift we need to account for here. Make a comment of it in the code as well.

Ex. Start Time of 6am might actually be 6:20am

2022-08-02 13:59 UTC, abitblue commented on interface/api-automatic.py
> +    def add_device(self, mac: str, device_name: str, notes: Optional[str] = None, enabled: bool = True, year: Optional[int] = 4) -> dict:
Missing `do_expire` action. Devices need to be purged from Clearpass once they can, because by default they linger around, but are just disabled.

2022-08-02 13:59 UTC, abitblue commented on interface/api-automatic.py
> +        if notes: fields['notes'] = notes
Python convention: please put on new line

2022-08-02 13:59 UTC, abitblue commented on interface/api-automatic.py
> +    def update_device(self, mac: str, expire_time: Optional[str] = None, notes: Optional[str] = None, enabled: bool = True, role_id: Optional[int] = 2) -> dict:
Missing option to update based on formatted username

2022-08-02 13:59 UTC, abitblue commented on interface/api-automatic.py
> +    def _get_expire_date(self, year: str) -> str:
`_get_expire_date()` ***

2022-08-02 13:59 UTC, abitblue commented on interface/wrapper.py
> +            self.mac = response['mac']
Does not account for users with multiple devices.

2022-08-02 15:57 UTC, IvanZ505 requested changes
see comments

2022-08-02 15:57 UTC, IvanZ505 commented on interface/api.py
> +            logging.warn(f'{userType} is not a valid User Type, setting expiration to no expiration.\nValid user types are: teacher, student, guest.')
do not hard code at all. we have settings for this in the database permissions table.

2022-08-02 15:57 UTC, IvanZ505 commented on interface/api.py
> +                                 )
you're searching for the same thing in both of these elif statements. Doesn't get us anywhere. If you can. include a way to search for whether a specific device is registered to a specific user through something like `if device_id is not None and mac is not None`

2022-08-02 15:58 UTC, abitblue requested changes

2022-08-02 15:58 UTC, abitblue commented on interface/wrapper.py
> +            self.mac = response['mac']
Still not accounting for multiple devices on one user?

2022-08-02 15:58 UTC, abitblue commented on interface/api.py
> +    def add_device(self, mac: str, username: str, userType: str, device_name: Optional[str] = None, enabled: bool = True, customTime: timedelta = None) -> dict:
userType should not be passed into any function here.

2022-08-02 15:58 UTC, abitblue commented on interface/api.py
> +        return result
These dates should never be hardcoded. There are specific settings for this in the database. Please give the option to accept a datetime or timedelta.

2022-08-02 15:58 UTC, abitblue commented on interface/api.py
> +                        self.token_expire_time = token_data["expires_in"] + self.current_time - 60
This is not timezone aware. What timezone does `token_data["expire_in"]` use? What does self.current_time use? Are you positive that we will always get seconds from the token data?

2022-08-02 15:58 UTC, abitblue commented on interface/api.py
> +                                'start_time': self._get_expire_date('custom', timedelta(minutes=20)) # ClearPass system clock 20 minutes faster
This implies a timedelta of +20 minutes doesn't it? We want a timedelta of -20 minutes.

2022-08-02 15:58 UTC, abitblue commented on interface/api.py
> +                                'do_expire': True,
`do_expire` is not a boolean. It takes an enum value.

2022-08-02 15:58 UTC, abitblue commented on interface/api.py
> +        if notes: fields['notes'] = notes
Still not on new line.

2022-08-02 15:58 UTC, abitblue commented on interface/api.py
> +        return check
We discussed that it might be better to call the wrapper function with the existing key, then if it fails, try again with a new key, and if it still fails, then raise an error.

2022-08-03 13:17 UTC, IvanZ505 requested changes

2022-08-03 13:17 UTC, IvanZ505 commented on interface/wrapper.py
>              pass
still not correct. basically all of these responses eg: `self.notes = response['notes']` may all have multiple returned responses. If a teacher has a phone on Clearpass and called it "Whalen's phone", and then has a computer connected called "Whalen's Mac", how are you catching that?

2022-08-03 13:17 UTC, IvanZ505 commented on interface/wrapper.py
>      sponsor_name: str = None
see the comment below.

2022-08-03 13:17 UTC, IvanZ505 commented on interface/api.py
> +            result = datetime.timestamp(time)
This is not going to work. If someone registers a device in the middle of the year, then it'll expire in 4 years, in the middle of the year? That's too inconsistent. We need all devices from that year to expire in 4 years, before the school year begins.

2022-08-03 13:17 UTC, IvanZ505 commented on interface/api.py
> +            result = datetime.timestamp(time)
How are you going to catch a null value? What are we doing if we want the device to never expire?

2022-08-04 12:43 UTC, IvanZ505 reviewed
ryan wants to look at it too

2022-08-04 12:43 UTC, IvanZ505 approved these changes

2022-08-08 14:41 UTC, abitblue requested changes
Very good overall. Fixing just a few things should be fine.

2022-08-08 14:41 UTC, abitblue commented on interface/api.py
> +                                'do_expire': 4,
Magic Numbers! Please write a comment explaining what these do.

2022-08-08 14:41 UTC, abitblue commented on interface/api.py
> +            result = datetime.timestamp(datetime.now() + time)
This datetime is not timezone aware. Please use `django.utils.timezone.now()` for a UTC datetime (our default timezone). Double check what timezone Clearpass uses, and convert as necessary.

2022-08-08 14:41 UTC, abitblue commented on interface/api.py
> +            result = datetime.timestamp(time)
Same here, double check what timezone Clearpass uses, and convert as necessary. Please only accept timezone-aware datetimes in your function signature.

2022-08-08 14:41 UTC, abitblue commented on interface/wrapper.py
> +        self.id = []
Seems ok. Have you considered using a list of devices (ie. `list[dict[str, str]]`) instead of lists of device attributes (ie. `list[list[str]]`) (which is what you have)

2022-08-08 16:32 UTC, harveyj123 commented on interface/wrapper.py
> +        self.id = []
using a dict makes more sense 👍

2022-08-08 16:50 UTC, IvanZ505 requested changes

2022-08-08 16:50 UTC, IvanZ505 commented on interface/api.py
>                                  'role_id': 2,
magic number!!! specify guest role!

2022-08-08 16:50 UTC, IvanZ505 commented on interface/wrapper.py
> +        self.id = []
please do this

2022-08-08 17:05 UTC, IvanZ505 approved these changes
CONGRATS!!!

2022-08-08 17:07 UTC, abitblue approved these changes
Seems okay. Merging and closing.

2022-08-08 17:07 UTC, merged